### ISSUE TITLE
pre-compile happen version error

### ISSUE THREAD

**Issue by kuangpeng** [lazd/gulp-handlebars#80] opened 2017-02-09 09:07 UTC
the dependencies of handlebars should be upgraded, old version not support run. ^3.0.0 is too old!

**Comment by lazd** [comment] 2017-02-09 14:53
Duplicate of #69. Honestly, I'm going to remove handlebars as a dependency and ask users to install the version they're expecting and require it themselves because this issue comes up way too often and project authors need to be responsible for their own dependency management.

Please see the `handlebars` option as documented in the readme.

**Closed by lazd** 2017-02-09 14:53 UTC
